// <auto-generated />
namespace WarstwaDostępuDoDanych.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dodaniepolozeniamiasta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodaniepolozeniamiasta));
        
        string IMigrationMetadata.Id
        {
            get { return "202301131037543_Dodanie polozenia miasta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
